# Generated by Django 4.1.12 on 2023-10-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDevices',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('_id', models.CharField(default='8129f7d73c274acb9f1443f3818db76b', editable=False, max_length=24, primary_key=True, serialize=False)),
                ('ipAddress', models.GenericIPAddressField(unique=True)),
                ('deviceUser', models.CharField(max_length=100)),
                ('devicePassword', models.CharField(max_length=100)),
                ('controllerStatus', models.CharField(max_length=40)),
                ('deviceName', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('macAddress', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainController.groupdevices')),
            ],
        ),
    ]
