# Generated by Django 4.1.12 on 2023-11-07 12:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='clientes',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.CharField(default='fdeeaf84f805440aaae6f3641c4a02ba', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
