# Generated by Django 4.1.13 on 2023-11-26 15:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='clientes',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.CharField(default='4a1ecf443e114ffe9264c2882cc0cd16', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
