# Generated by Django 4.1.12 on 2023-11-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0002_devices_clientes_alter_devices__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='clientes',
        ),
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.AutoField(default='5d9bb092f917457a90e523f88e9d9eaf', editable=False, primary_key=True, serialize=False),
        ),
    ]
