# Generated by Django 4.1.12 on 2024-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0002_devices_clientes_alter_devices__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.CharField(default='d33fe5f03f2f42a2b83e726b4ff6d814', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
