# Generated by Django 4.1.12 on 2023-10-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainController', '0002_delete_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.GenericIPAddressField(unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('controllerStatus', models.CharField(max_length=40)),
                ('hostName', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('macAddress', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
