# Generated by Django 4.1.12 on 2023-11-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0003_remove_devices_clientes_alter_devices__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
