# Generated by Django 4.1.13 on 2024-06-27 14:54

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0003_controllers'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllers',
            name='rkzones',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
