# Generated by Django 4.1.13 on 2024-06-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0004_controllers_rkzones'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllers',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='controllers',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
