# Generated by Django 4.1.12 on 2023-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0004_alter_devices__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.CharField(default='b3d0a055e697413a9d7ce2592fa75dcf', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
