# Generated by Django 4.1.12 on 2023-10-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
