# Generated by Django 4.1.12 on 2023-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0005_alter_devices__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.CharField(default='8178bc6163d84a699548264711d1aad7', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
