# Generated by Django 4.1.12 on 2023-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0006_alter_devices__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='_id',
            field=models.CharField(default='11d5978637dd46f188f52c25bcadc6d4', editable=False, max_length=24, primary_key=True, serialize=False),
        ),
    ]
